// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppList():Promise<Array<string>>;

export function StartApp(arg1:string):Promise<string>;
