// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppList() {
  return window['go']['main']['App']['AppList']();
}

export function StartApp(arg1) {
  return window['go']['main']['App']['StartApp'](arg1);
}
